config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  include Paginatable

  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article

  validates :commenter, presence: true
  validates :content, presence: true
end

app/models/concerns/paginatable.rb
module Paginatable
  extend ActiveSupport::Concern

  PER_PAGE_OPTIONS = [25, 50, 100].freeze

  included do
    def self.search_page(page, per, order = :asc)
      per_page = per.blank? ? Paginatable::PER_PAGE_OPTIONS.first : per.to_i
      total_count = self.count
      current_page = (page.to_i - 1) < 0 ? 0 : page.to_i - 1

      if current_page.zero?
        records = limit(per_page)
      else
        if order == :desc
          records = where("id <= ?", ((total_count / per_page.to_f).ceil - current_page) * per_page).limit(per_page)
        else
          records = where("id > ?", current_page * per_page).limit(per_page)
        end
      end

      {
        records: records,
        current_page: current_page,
        total_pages: (total_count / per_page.to_f).ceil,
        per_page: per_page
      }
    end
  end
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def published_count
      published.count
    end

    def published
      where(status: 'public')
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/weather_importer.rb
class WeatherImporter
  def self.execute

    pref_ja = URI.encode_www_form_component("東京")
    address = URI.encode_www_form_component("世田谷")
    # uri = URI.parse("https://jjwd.info/api/v2/stations/search?pref_ja=#{pref_ja}&address=#{address}")
    uri = URI.parse('https://api.open-meteo.com/v1/forecast?latitude=35.6785&longitude=139.6823&hourly=temperature_2m&timezone=Asia%2FTokyo')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    res = http.get(uri.request_uri)
    return if res.code != '200'

    r = JSON.parse(res.body, symbolize_names: true)
    r[:hourly][:time]
    r[:hourly][:temperature_2m]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  include Paginatable

  def index
    @pagination = Article.order(updated_at: "DESC").search_page(params[:page], params[:per_page], :desc)
    @articles = @pagination[:records]
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      render :create
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to article_url(@article), flash: { success: "記事を更新しました。" }
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.js   { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    render turbo_stream: turbo_stream.remove(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content,:status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :content, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/paginatable_helper.rb
module PaginatableHelper
  def paginate(records)
    locals = {
      current_page: records[:current_page],
      total_pages: records[:total_pages],
      per_page: records[:per_page],
    }
    render partial: "shared/pagination", locals: locals
  end
end

app/views/articles/_article.html.erb
<%= turbo_frame_tag article do %>
  <div class="card">
    <div class="card-body">
      <%= article.title %>
      <%= link_to "Show", article, class: "btn btn-secondary mr-2" %>
      <%= link_to "Edit", edit_article_path(article), class: "btn btn-primary mr-2" %>
      <%= link_to "Destroy", article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: article) do |form| %>
      <div><%= form.text_field :title %></div>
      <div><%= form.text_area :content %></div>
      <div><%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %></div>
      <div><%= form.submit %></div>
    <% end %>
    <div><%= link_to "Back to articles", articles_path, class: "btn btn-primary mr-2" %></div>
  </div>
</div>

app/views/articles/_new_button.html.erb
<%= turbo_frame_tag 'new_article' do %>
  <%= link_to 'New', new_article_path , class: 'btn btn-primary mb-4' %>
<% end %>

app/views/articles/create.turbo_stream.erb
<%= turbo_stream.prepend 'articles' do %>
  <%= render @article %>
<% end %>

<%= turbo_stream.replace 'new_article' do %>
  <%= render "new_button" %>
<% end %>

app/views/articles/edit.html.erb
<%= turbo_frame_tag @article do %>
  <%= render "form", article: @article %>
<% end %>

app/views/articles/index.html.erb
<!-- app/views/articles/index.html.erb -->
<h1 class="text-center">Articles</h1>

<div class="row justify-content-center">
  <div class="col-8 mb-4">
    <%= render "new_button" %>
  </div>

  <div class="col-8 mb-4">
    <%= turbo_frame_tag 'articles' do %>
      <%= paginate @pagination %>
      <%= render @articles %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<%= turbo_frame_tag @article do %>
  <%= render "form", article: @article %>
<% end %>

app/views/articles/show.html.erb
<%= turbo_frame_tag @article do %>
  <div class="card">
    <div class="card-body">
      <%= @article.title %>
      <%= @article.content %>
      <%= @article.status %>
      <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary mr-2" %>
    </div>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.content %>
</p>

<p>
  <%= link_to "Destroy Comment", [comment.article, comment], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<div>フッター</div>

app/views/layouts/_header.html.erb
<div>ヘッダー</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
    <%= message %>
    <% if object && object.errors.any? %>
      <% enumerator = object.errors.respond_to?(:full_messages) ? object.errors.full_messages : object.errors %>
      <ul>
        <% enumerator.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<!-- app/views/shared/_pagination.html.erb -->
<div class="d-flex justify-content-between align-items-center mb-3">
  <div>
    <% current_path = url_for == "/" ? "/#{controller_name}" : url_for %>
    <%= form_tag(current_path, method: :get, id: "pagination-form") do %>
      <%= select_tag :per_page, options_for_select(Paginatable::PER_PAGE_OPTIONS, per_page), class: "form-select w-auto", onchange: "this.form.submit()" %>
    <% end %>
  </div>

  <nav aria-label="Page navigation">
    <ul class="pagination">
      <% (0...total_pages).each do |page| %>
        <li class="page-item <%= 'active' if current_page == page %>">
          <%= link_to page + 1, "/#{controller_name}?page=#{page + 1}&per_page=#{per_page}", class: "page-link", data: { turbo_action: "replace", turbo_target: "articles" }, remote: true %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>